version: '3.8'

services:

  php-fpm:
    container_name: php-fpm
    build:
      context: ./php-fpm
    volumes:
      - ./../:/var/www
      - /dev/null:/var/www/docker

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ./../:/var/www
      - /dev/null:/var/www/docker
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
      - ./certbot/data:/var/www/certbot
      - ./certbot/conf:/etc/nginx/ssl
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"